image:
  repository: sudnya/scalarlm-rocm
  tag: v0.8
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8200
  vllm_port: 8201
  externalIP: 64.139.222.101

jobs_pvc:
  storageClass: local-path
  size: 100Gi

cache_pvc:
  storageClass: local-path
  size: 200Gi

model: meta-llama/Llama-3.3-70B-Instruct
max_model_length: 4096
gpu_memory_utilization: 0.95

training_gpus: 2
inference_gpus: 1

max_train_time: 86400
