image:
  repository: gdiamos/scalarlm-amd
  tag: v0.95
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8000
  vllm_port: 8001
  externalIP: 64.139.222.101

jobs_pvc:
  storageClass: local-path
  size: 100Gi

cache_pvc:
  storageClass: local-path
  size: 200Gi

model: meta-llama/Llama-3.3-70B-Instruct
max_model_length: 16384
gpu_memory_utilization: 0.92
dtype: bfloat16

training_gpus: 2
inference_gpus: 6

max_train_time: 86400
