#!/bin/bash

# Safely execute this bash script
set -Eeuoxa pipefail

# Get the directory of this script
LOCAL_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Only regenerate if the generated CLI script is missing
if [ ! -f "$LOCAL_DIRECTORY/scripts/scalarlm" ]; then
    $LOCAL_DIRECTORY/cmd/bashly.sh generate
fi

# Call the generated CLI script
$LOCAL_DIRECTORY/scripts/scalarlm "$@"
