image:
  repository: gdiamos/scalarlm-amd
  tag: v0.951
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8000
  vllm_port: 8001
  externalIP: 64.139.222.101

jobs_pvc:
  storageClass: longhorn
  size: 100Gi

cache_pvc:
  storageClass: longhorn
  size: 200Gi

slurm_config_pvc:
  storageClass: longhorn
  size: 10Gi

cloudflared:
  tunnelToken: eyJhIjoiMDhmMjU0OGRjYWJmOGJhNDI0Y2M2ZTY0MDdkYmQzZDQiLCJ0IjoiMDdjOTE0NTgtMDhiOC00Yjg5LWJiMTAtZjE0MDI2ZjY5ZGY0IiwicyI6Ik5UaGhaVGRoTlRFdE9UVm1aaTAwTkdabExUZzFNV1l0WVdOaE9ETTBZamt3WkdFMSJ9

model: meta-llama/Llama-3.2-3B-Instruct
max_model_length: 8192
gpu_memory_utilization: 0.95

training_gpus: 2
inference_gpus: 1

max_train_time: 86400
