image:
  repository: gdiamos/scalarlm-amd
  tag: v0.99
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8000
  vllm_port: 8001
  externalIP: 64.139.222.101

jobs_pvc:
  storageClass: longhorn
  size: 100Gi

cache_pvc:
  storageClass: longhorn
  size: 400Gi

slurm_config_pvc:
    storageClass: longhorn
    size: 10Gi

model: Qwen/Qwen3-32B
max_model_length: 8192
gpu_memory_utilization: 0.80
dtype: bfloat16

training_gpus: 2
inference_gpus: 1

max_train_time: 86400
