apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalarlm.megatronname" . }}-headless
  labels:
    {{- include "scalarlm.megatronlabels" . | nindent 4 }}
spec:
  clusterIP: None  # This makes it headless
  selector:
    {{- include "scalarlm.megatronlabels" . | nindent 4 }}
  ports:
    - port: 6818     
      targetPort: 6818 
      protocol: TCP
