apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalarlm.vllmname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.vllm_port }}  
      targetPort: 8001
      protocol: TCP
      name: http
  externalIPs:
    - {{ .Values.service.externalIP }}
  selector:
    {{- include "scalarlm.vllmlabels" . | nindent 4 }}
