apiVersion: v1
kind: Service
metadata:
  name: {{ include "scalarlm.fullname" . }}
  labels:
    {{- include "scalarlm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api_port }}
      targetPort: api
      protocol: TCP
      name: http
    - port: {{ .Values.service.ui_port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.service.slurmctld_port }}
      targetPort: {{ .Values.service.slurmctld_port }}
      protocol: TCP
      name: slurmctld
  selector:
    {{- include "scalarlm.selectorLabels" . | nindent 4 }}
